UBUNTU: SAUCE: ubuntu_cve_kernel: integrate blacklist rule into control file
Experiment shows that only CVE-2016-3672 test cannot be built on
non-x86 systems, it will fail because of the -m32 flag:
   fatal error: bits/libc-header-start.h: No such file or directory

Integrate the arch-specific blacklist setting into sub tests. Also
remove some out-dated series blacklists.

Change the way how we build the test, with this patch sub-tests will
be build and run while being tested, instead of being built altogether
at the very beginning. So that we can make use of the integrated
blacklist for skipping tests.

Patch tested on Focal PowerPC and Bionic s390x

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>