UBUNTU: SAUCE: ubuntu_performance_pts: fix missing name variable
We are using the NAME variable for the test name, correct this for
sub-tests to fix the NameError issue:
    NameError: name 'name' is not defined

Fixes: 48b0e64c21 ("UBUNTU: SAUCE: ubuntu_performance_*: allow test
to abort if setup() has failed")
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>