UBUNTU: SAUCE: ubuntu_qrt_apparmor: ensure g++ is up-to-date for Jammy
BugLink: https://bugs.launchpad.net/bugs/2103671
Test shows in the J/xilinx image, the g++-11 is not up-to-date and
thus causing undefined reference to `__aarch64_ldadd4_sync' build
error when running the test_parser_testsuite test.

Ask the test to install g++-11 on Jammy to fix this issue.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>