UBUNTU: SAUCE: ubuntu_zfs_smoke_test: Fix test name mismatch issue
There is a test name mismatch issue casuing the following error:
  Traceback (most recent call last):
    File "/home/ubuntu/autotest/client/parallel.py", line 25, in fork_start
      l()
    File "/home/ubuntu/autotest/client/job.py", line 505, in
      l = lambda: test.runtest(self, url, tag, args, dargs)
    File "/home/ubuntu/autotest/client/test.py", line 125, in runtest
      job.sysinfo.log_after_each_iteration)
    File "/home/ubuntu/autotest/client/shared/test.py", line 880, in runtest
      raise error.TestError(testname + ': test does not exist')
  TestError: ubuntu_zfs_smoke_tests: test does not exist

Correct the test name to fix this.

Fixes: ecdb75003f ("UBUNTU: SAUCE: ubuntu_zfs_*: allow test to abort if setup() has failed")
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>