UBUNTU: SAUCE: ubuntu_lxc: intall systemd-dev package for Noble+
BugLink: https://bugs.launchpad.net/bugs/2089812

We need to install systemd-dev for building this test on Oracular.
Otherwise it will fail with:
  ERROR: Dependency "systemd" not found, tried pkgconfig)

As this package was installed on Noble by default, it's OK to reuse
the existing if statment and install it for Noble and newer.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>