UBUNTU: SAUCE: ubuntu_bpf: fix 'Kernel configuration is invalid' build issue
BugLink: https://bugs.launchpad.net/bugs/1948831

Fix the test build issue for newer kernels:
  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

Makefile:669: include/config/auto.conf: No such file or directory

Patch tested with Kinetic AWS 5.19

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>